'''
Jeremy Chan 2020
Analysis tool for reading pkl of earnings data generated by scraper.py

--------------------------
REVISION HISTORY
10/20 - Created
--------------------------
'''
import sys
sys.path.insert(1,'web_scraper/')
import pandas as pd
import matplotlib as mp

def readPickle():
    f = open("10_25_2020_earnings.pkl", "rb")
    data = pickle.load(f)
    print(data)

